server:
  port: 80
spring:
    application:
      name: cloud-order-service

eureka:
  client:
    # 表示是否将自己注册进eureka server 默认为true
    register-with-eureka: true
    # 是否从eureka抓取已有的注册信息, 默认为true, 单节点无所谓, 集群必须设置为true才能使用ribbon负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/,http://eureka7002.com:7002/,http://eureka7003.com:7003/

mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.start.springcloud.entities    # 所有Entity别名类所在包