server:
  port: 8005
spring:
  application:
    name: cloud-payment-service
  cloud:
    consul:
      host: 124.71.200.219
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        heartbeat:
          enabled: true
        prefer-ip-address: true
        hostname: 192.168.3.7